[package]
name = "core"
version = "0.0.1"
authors = ["pomcho555 <pomcho555@users.noreply.github.com>"]
description = "The application core code"
edition = "2024"

[dependencies]
utils = { path = "../utils" }

rand = "0.8"
log = "0.4"
